# Generated by Django 4.1.2 on 2022-11-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='OptA',
        ),
        migrations.AddField(
            model_name='question',
            name='optB',
            field=models.CharField(default='oes', max_length=40),
        ),
        migrations.AddField(
            model_name='question',
            name='optC',
            field=models.CharField(default='oes', max_length=40),
        ),
        migrations.AddField(
            model_name='question',
            name='optD',
            field=models.CharField(default='oes', max_length=40),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques',
            field=models.CharField(default='oes', max_length=140),
        ),
        migrations.AddField(
            model_name='question',
            name='optA',
            field=models.CharField(default='oes', max_length=40),
        ),
    ]
