# Generated by Django 4.1.2 on 2022-11-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_question_id_question_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qno',
            new_name='qnos',
        ),
    ]
