# Generated by Django 4.1.2 on 2022-11-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_rename_qno_question_qnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default=' ', max_length=1),
        ),
    ]
