# Generated by Django 4.1.3 on 2022-12-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('realname', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
