# Generated by Django 4.1.2 on 2022-12-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_course_question_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default='oes', max_length=1),
        ),
    ]
