# Generated by Django 4.1.3 on 2022-12-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_question_marks_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.IntegerField(default=1),
        ),
    ]
