# Generated by Django 4.1.3 on 2022-12-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=1),
        ),
    ]
