# Generated by Django 4.1.3 on 2022-12-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='negative_marking',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='negative_marks',
            field=models.FloatField(default=0),
        ),
    ]
