# Generated by Django 4.1.3 on 2022-12-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_course_date_course_scheduled_exam_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(default='A', max_length=20),
        ),
    ]
